// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type Link struct {
	ID          int32
	OriginalUrl string
	ShortCode   string
	UserID      sql.NullInt32
	Visits      sql.NullInt32
	CreatedAt   sql.NullTime
	ExpiredAt   sql.NullTime
}

type User struct {
	ID        int32
	Email     string
	Password  string
	CreatedAt sql.NullTime
}
