// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
	"database/sql"
)

const createLink = `-- name: CreateLink :execresult
INSERT INTO links (original_url, short_code, user_id)
VALUES (?, ?, ?)
`

type CreateLinkParams struct {
	OriginalUrl string
	ShortCode   string
	UserID      sql.NullInt32
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createLink, arg.OriginalUrl, arg.ShortCode, arg.UserID)
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (email, password)
VALUES (?, ?)
`

type CreateUserParams struct {
	Email    string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser, arg.Email, arg.Password)
}

const getLinkByCode = `-- name: GetLinkByCode :one
SELECT id, original_url, short_code, user_id, visits, created_at, expired_at FROM links
WHERE short_code = ? LIMIT 1
`

func (q *Queries) GetLinkByCode(ctx context.Context, shortCode string) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLinkByCode, shortCode)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.UserID,
		&i.Visits,
		&i.CreatedAt,
		&i.ExpiredAt,
	)
	return i, err
}

const getLinksByUser = `-- name: GetLinksByUser :many
SELECT id, original_url, short_code, user_id, visits, created_at, expired_at FROM links
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetLinksByUser(ctx context.Context, userID sql.NullInt32) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, getLinksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.ShortCode,
			&i.UserID,
			&i.Visits,
			&i.CreatedAt,
			&i.ExpiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, created_at FROM users
WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}
